### ISSUE TITLE
AttributeError: object has no attribute 'tmdb_movieid'

### ISSUE THREAD

**Issue by SirJohnDoe** [suka97/letterboxd2plex#1]
Thanks for this script. Unforunately I can't get it to work due to this error. My RSS link is as follows, and contains the 'tmdb:movieid' for every line so not sure what the issue is: https://letterboxd.com/sirjohndoe/rss/

> `C:\Program Files\Plex\letterboxd2plex-main>python letterboxd2plex.py --config config.yml
> Traceback (most recent call last):
>   File "C:\Users\John\AppData\Local\Programs\Python\Python312\Lib\site-packages\feedparser\util.py", line 156, in __getattr__
>     return self.__getitem__(key)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\John\AppData\Local\Programs\Python\Python312\Lib\site-packages\feedparser\util.py", line 113, in __getitem__
>     return dict.__getitem__(self, key)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: 'tmdb_movieid'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Program Files\Plex\letterboxd2plex-main\letterboxd2plex.py", line 40, in <module>
>     "tmdb": entry.tmdb_movieid,
>             ^^^^^^^^^^^^^^^^^^
>   File "C:\Users\John\AppData\Local\Programs\Python\Python312\Lib\site-packages\feedparser\util.py", line 158, in __getattr__
>     raise AttributeError("object has no attribute '%s'" % key)
> AttributeError: object has no attribute 'tmdb_movieid'`

**Comment by suka97** [comment]
Hi thanks for the feedback!

The error was related to your ratings including tv series (in this case "The Pacific" and "Masters of the Air"). I had not taken into account that Letterboxd allows users to rate some tv shows.

I've updated the script to skip the items if they are not movies (if it can't find the property tmdb_id). Please give it a try and let me know

**Comment by SirJohnDoe** [comment]
Ah I missed those myself, I checked for the ID but I saw that every line had one. Didn't think about the 'tvID'. It works great now, thanks a lot!
